import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col h-screen bg-background">
          <Navbar />
          <main className="h-full flex items-center justify-center p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}

function Navbar() {
  return (
    <div className="flex justify-center items-center p-2 gap-4">
      <NavLink href="/">Home</NavLink>
      <NavLink href="/style">Style</NavLink>
    </div>
  );
}

function NavLink({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <Link href={href} className="rounded-md">
      <div className="px-2 py-1 hover:underline">{children}</div>
    </Link>
  );
}
